### PR TITLE
New inspec deps

### PR DESCRIPTION
**Pull request by nsdavidson**
Latest versions of inspec/train/inspec-scap pulled in a few new deps
that need license info.

Signed-off-by: Nolan Davidson <ndavidson@chef.io>

### CODE REVIEW

**Comment by btm** [comment]
@nsdavidson what version of Inspec did we pull in? this seems like a lot of new deps for being pinned to inspec 1.

**Comment by nsdavidson** [comment]
@btm It looks like it was mostly from train for GCP support.

https://github.com/inspec/train/blob/master/CHANGELOG.md#v149-2018-05-16

**Comment by btm** [comment]
@chris-rock do we need more than inspec-core for A1?

@nsdavidson forking `omnibus-software/config/software/inspec.rb` to a `inspec-core.rb` that builds the `inspec-core` gem should get us `train-core` instead which ideally is closer to what we need in A1.

**Comment by chris-rock** [comment]
@btm inspec-core works perfectly for A1

**Pull request merged**
